name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull latest changes on Raspberry Pi
      run: |
        cd /home/pi/boxbot/ТГ_БОТ_КОРОБОЧКИ
        git pull
        sudo systemctl restart boxbot.service

