name: Deploy to Raspberry Pi (self-hosted)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show environment (debug)
        run: |
          whoami
          hostname
          pwd

      - name: Deploy bot
        run: |
          set -e
          cd /home/pi/boxbot
          git pull origin master

      - name: Restart service
        run: |
          sudo systemctl restart boxbot.service

      - name: Health check
        run: |
          sleep 5
          systemctl is-active boxbot.service

